Collections:
- Name: TANet
  README: configs/recognition/tanet/README.md
Models:
- Config: configs/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb.py
  In Collection: TANet
  Metadata:
    Architecture: TANet
    Batch Size: 8
    Epochs: 100
    Parameters: 25590320
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 8 GPUs
  Modality: RGB
  Name: tanet_r50_dense_1x1x8_100e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 76.28
      top5 acc: 92.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219-032c8e94.pth
