Collections:
  - Name: TANet
    README: configs/recognition/tanet/README.md
    Paper:
      URL: https://arxiv.org/abs/2005.06803
      Title: "TAM: Temporal Adaptive Module for Video Recognition"

Models:
  - Name: tanet_r50_dense_1x1x8_100e_8xb8_kinetics400_rgb
    Config: configs/recognition/tanet/tanet_r50_dense_1x1x8_100e_8xb8_kinetics400_rgb.py
    In Collection: TANet
    Metadata:
      Architecture: TANet
      Batch Size: 8
      Epochs: 100
      FLOPs: 43065983104
      Parameters: 25590320
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 76.22
        Top 5 Accuracy: 92.31
#    Training Json Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.json
#    Training Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.log
#    Weights: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219-032c8e94.pth
