Collections:
- Name: TANet
  README: configs/recognition/tanet/README.md
Models:
- Config: configs/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb.py
  In Collection: TANet
  Metadata:
    Architecture: TANet
    Batch Size: 8
    Epochs: 100
    FLOPs: 43065983104
    Parameters: 25590320
    Pretrained: ImageNet
    Resolution: short-side 320
    Training Data: Kinetics-400
    Training Resources: 8 GPUs
  Modality: RGB
  Name: tanet_r50_dense_1x1x8_100e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      Top 1 Accuracy: 76.28
      top5 accuracy: 92.6
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_dense_1x1x8_100e_kinetics400_rgb/tanet_r50_dense_1x1x8_100e_kinetics400_rgb_20210219-032c8e94.pth
- Config: configs/recognition/tanet/tanet_r50_1x1x8_50e_sthv1_rgb.py
  In Collection: TANet
  Metadata:
    Architecture: TANet
    Batch Size: 8
    Epochs: 50
    FLOPs: 32972787840
    Parameters: 25127246
    Pretrained: ImageNet
    Resolution: height 100
    Training Data: SthV1
    Training Resources: 8 GPUs
  Modality: RGB
  Name: tanet_r50_1x1x8_50e_sthv1_rgb
  Results:
  - Dataset: SthV1
    Metrics:
      Top 1 Accuracy: 49.69
      Top 1 Accuracy (efficient): 47.45
      top5 accuracy: 77.62
      top5 accuracy (efficient): 76.0
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x8_50e_sthv1_rgb/20210606_205006.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x8_50e_sthv1_rgb/20210606_205006.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x8_50e_sthv1_rgb/tanet_r50_1x1x8_50e_sthv1_rgb_20210630-f4a48609.pth
- Config: configs/recognition/tanet/tanet_r50_1x1x16_50e_sthv1_rgb.py
  In Collection: TANet
  Metadata:
    Architecture: TANet
    Batch Size: 8
    Epochs: 50
    FLOPs: 65946542336
    Parameters: 25134670
    Pretrained: ImageNet
    Resolution: height 100
    Training Data: SthV1
    gpus: 4
  Modality: RGB
  Name: tanet_r50_1x1x16_50e_sthv1_rgb
  Results:
  - Dataset: SthV1
    Metrics:
      Top 1 Accuracy: 50.41
      Top 1 Accuracy (efficient): 47.73
      top5 accuracy: 78.47
      top5 accuracy (efficient): 77.31
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x16_50e_sthv1_rgb/20210607_155335.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x16_50e_sthv1_rgb/20210607_155335.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tanet/tanet_r50_1x1x16_50e_sthv1_rgb/tanet_r50_1x1x16_50e_sthv1_rgb_20210630-7c19303c.pth
