assign:
  issues: enable
  pull_requests: disable
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
    - hukkai
    - Dai-Wenxun
    - cir7
    - Dai-Wenxun
    - cir7
