assign:
  issues: enabled
  pull_requests: disabled
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
    - hukkai
    - Dai-Wenxun
    - cir7
    - Dai-Wenxun
    - cir7
    - hukkai
    - hukkai
