Collections:
- Name: AVA
  README: configs/detection/ava/README.md
  Paper:
    URL: https://arxiv.org/abs/1705.08421
    Title: "AVA: A Video Dataset of Spatio-temporally Localized Atomic Visual Actions"

Models:
  - Name: slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb
    Config: configs/detection/ava/slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 20.76
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb_20220906-953ef5fe.pth

  - Name: slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb
    Config: configs/detection/ava/slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-700
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 22.77
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics700-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb_20220906-b3b6d44e.pth

  - Name: slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb
    Config: configs/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 21.49
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50-nl_8xb16-4x16x1-20e_ava21-rgb_20220906-5ae3f91b.pth

  - Name: slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb
    Config: configs/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 23.47
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r50-nl_8xb16-8x8x1-20e_ava21-rgb_20220906-9760eadb.pth

  - Name: slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb
    Config: configs/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet101
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 24.82
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb/slowonly_kinetics400-pretrained-r101_8xb16-8x8x1-20e_ava21-rgb_20220906-43f16877.pth

  - Name: slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb
    Config: configs/detection/ava/slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 24.27
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50_8xb16-4x16x1-20e_ava21-rgb_20220906-5180ea3c.pth

  - Name: slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb
    Config: configs/detection/ava/slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 25.25
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50-context_8xb16-4x16x1-20e_ava21-rgb_20220906-5bb4f6f2.pth

  - Name: slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb
    Config: configs/detection/ava/slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 25.73
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb/slowfast_kinetics400-pretrained-r50_8xb8-8x8x1-20e_ava21-rgb_20220906-39133ec7.pth

  - Name: slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb
    Config: configs/detection/ava/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 6
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.2
        Task: Action Detection
        Metrics:
              mAP: 25.98
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_kinetics400-pretrained-r50_8xb6-8x8x1-cosine-10e_ava22-rgb_20220906-d934a48f.pth

  - Name: slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb
    Config: configs/detection/ava/slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 6
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.2
        Task: Action Detection
        Metrics:
              mAP: 26.38
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_kinetics400-pretrained-r50-temporal-max_8xb6-8x8x1-cosine-10e_ava22-rgb_20220906-13a9078e.pth

  - Name: slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb
    Config: configs/detection/ava/slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb.py
    In Collection: AVA
    Metadata:
      Architecture: ResNet50
      Batch Size: 6
      Epochs: 20
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.2
        Task: Action Detection
        Metrics:
              mAP: 26.59
    Training Log: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/detection/ava/slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb/slowfast_r50-k400-pre-temporal-max-focal-alpha3-gamma1_8xb6-8x8x1-cosine-10e_ava22-rgb_20220906-dd59e26f.pth
