Collections:
- Name: ASFormer
  README: configs/segmentation/asformer/README.md
  Paper:
    URL: https://arxiv.org/pdf/2110.08568.pdf
    Title: "ASFormer: Transformer for Action Segmentation"

Models:
  - Name: asformer_1xb1-120e_gtea-split2-i3d-feature
    Config: configs/segmentation/asformer/asformer_1xb1-120e_gtea-split2-i3d-feature.py
    In Collection: ASFormer
    Metadata:
      Batch Size: 1
      Epochs: 120
      Training Data: GTEA
      Training Resources: 1 GPU
    Modality: RGB
    Results:
      - Dataset: GTEA split2
        Task: Action Segmentation
        Metrics:
              Acc: 80.34
              Edit: 81.58
              F1@10: 89.30
              F1@25: 87.83
              F1@50: 75.28
    Training Log: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_50salads-split2-i3d-feature.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_50salads-split2-i3d-feature_20231011-25dc57d5.pth

  - Name: asformer_1xb1-120e_50salads-split2-i3d-feature
    Config: configs/segmentation/asformer/asformer_1xb1-120e_50salads-split2-i3d-feature.py
    In Collection: ASFormer
    Metadata:
      Batch Size: 1
      Epochs: 120
      Training Data: 50salads
      Training Resources: 1 GPU
    Modality: RGB
    Results:
      - Dataset: 50salads split2
        Task: Action Segmentation
        Metrics:
              Acc: 87.55
              Edit: 79.10
              F1@10: 85.17
              F1@25: 83.73
              F1@50: 77.99
    Training Log: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_gtea-split2-i3d-feature.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_gtea-split2-i3d-feature_20231011-b5aaf789.pth

  - Name: asformer_1xb1-120e_breakfast-split2-i3d-feature
    Config: configs/segmentation/asformer/asformer_1xb1-120e_breakfast-split2-i3d-feature.py
    In Collection: ASFormer
    Metadata:
      Batch Size: 1
      Epochs: 120
      Training Data: breakfast
      Training Resources: 1 GPU
    Modality: RGB
    Results:
      - Dataset: breakfast split2
        Task: Action Segmentation
        Metrics:
              Acc: 74.12
              Edit: 76.53
              F1@10: 77.74
              F1@25: 72.62
              F1@50: 60.43
    Training Log: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_breakfast-split2-i3d-feature.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/segmentation/asformer/asformer_1xb1-120e_breakfast-split2-i3d-feature_20231011-10e557f3.pth
