MODEL:
  META_ARCHITECTURE: "GRiT"
  MASK_ON: True
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  FPN:
    IN_FEATURES: ["layer3", "layer4", "layer5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_HEADS:
    NAME: GRiTROIHeadsAndTextDecoder
    IN_FEATURES: ["p3", "p4", "p5"]
    IOU_THRESHOLDS: [0.6]
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.02
    NMS_THRESH_TEST: 0.5
    OBJECT_FEAT_POOLER_RES: 14
  ROI_BOX_CASCADE_HEAD:
    IOUS: [0.6, 0.7, 0.8]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
    MULT_PROPOSAL_SCORE: True
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: True
  CENTERNET:
    NUM_CLASSES: 1
    REG_WEIGHT: 1.
    NOT_NORM_REG: True
    ONLY_PROPOSAL: True
    WITH_AGN_HM: True
    INFERENCE_TH: 0.0001
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 256
    NMS_TH_TRAIN: 0.9
    NMS_TH_TEST: 0.9
    POS_WEIGHT: 0.5
    NEG_WEIGHT: 0.5
    IGNORE_HIGH_FP: 0.85
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1]
  DATASET_INPUT_SIZE: [1024]
  DATASET_INPUT_SCALE: [[0.1, 2.0]]
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
TEST:
  DETECTIONS_PER_IMAGE: 256
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  MAX_ITER: 180000
  IMS_PER_BATCH: 64
  BASE_LR: 0.00008
  VIT_LAYER_DECAY: True
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
USE_ACT_CHECKPOINT: True
VERSION: 2
