Collections:
- Metadata:
    Training Data: null
  Name: TIN
  README: configs/recognition/tin/README.md
Models:
- Config: configs/recognition/tin/tin_r50_1x1x8_40e_sthv1_rgb.py
  In Collection: TIN
  Metadata:
    Architecture: ResNet50
    Epochs: 40
    Parameters: 23895566
    Training BatchSize / GPU: 6
    Training Data: SthV1
    gpus: 32
    pretrain: ImageNet
    resolution: height 100
  Modality: RGB
  Name: tin_r50_1x1x8_40e_sthv1_rgb
  Results:
  - Dataset: SthV1
    Metrics:
      top1 acc: 44.25
      top5 acc: 73.94
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv1_rgb/20200729_034132.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv1_rgb/20200729_034132.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv1_rgb/tin_r50_1x1x8_40e_sthv1_rgb_20200729-4a33db86.pth
  gpu_mem(M): '6181'
- Config: configs/recognition/tin/tin_r50_1x1x8_40e_sthv2_rgb.py
  In Collection: TIN
  Metadata:
    Architecture: ResNet50
    Epochs: 40
    Parameters: 23895566
    Training BatchSize / GPU: 6
    Training Data: SthV2
    gpus: 32
    pretrain: ImageNet
    resolution: height 240
  Modality: RGB
  Name: tin_r50_1x1x8_40e_sthv2_rgb
  Results:
  - Dataset: SthV2
    Metrics:
      top1 acc: 56.7
      top5 acc: 83.62
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv2_rgb/20200912_225451.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv2_rgb/20200912_225451.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tin/tin_r50_1x1x8_40e_sthv2_rgb/tin_r50_1x1x8_40e_sthv2_rgb_20200912-b27a7337.pth
  gpu_mem(M): '6185'
- Config: configs/recognition/tin/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb.py
  In Collection: TIN
  Metadata:
    Architecture: ResNet50
    Epochs: 50
    Parameters: 24358640
    Training BatchSize / GPU: 6
    Training Data: Kinetics-400
    gpus: 32
    pretrain: TSM-Kinetics400
    resolution: short-side 256
  Modality: RGB
  Name: tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb
  Results:
  - Dataset: Kinetics-400
    Metrics:
      top1 acc: 70.89
      top5 acc: 89.89
    Task: Action Recognition
  Training Json Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb/20200809_142447.log.json
  Training Log: https://download.openmmlab.com/mmaction/recognition/tin/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb/20200809_142447.log
  Weights: https://download.openmmlab.com/mmaction/recognition/tin/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb_20200810-4a146a70.pth
  gpu_mem(M): '6187'
