Collections:
  - Name: TimeSformer
    README: configs/recognition/timesformer/README.md
    Paper:
      URL: https://arxiv.org/abs/2102.05095
      Title: 'Is Space-Time Attention All You Need for Video Understanding'

Models:
  - Name: timesformer_divST_8x32x1_15e_8xb8_kinetics400_rgb
    Config: configs/recognition/timesformer/timesformer_divST_8x32x1_15e_8xb8_kinetics400_rgb.py
    In Collection: TimeSformer
    Metadata:
      Architecture: TimeSformer
      Batch Size: 8
      Epochs: 15
      Pretrained: ImageNet-21K
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 77.96
        Top 5 Accuracy: 93.57
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_divST_8x32x1_15e_8xb8_kinetics400_rgb/20220614_113611.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_divST_8x32x1_15e_8xb8_kinetics400_rgb/timesformer_divST_8x32x1_15e_8xb8_kinetics400_rgb_20220815-a4d0d01f.pth

  - Name: timesformer_jointST_8x32x1_15e_8xb8_kinetics400_rgb
    Config: configs/recognition/timesformer/timesformer_jointST_8x32x1_15e_8xb8_kinetics400_rgb.py
    In Collection: TimeSformer
    Metadata:
      Architecture: TimeSformer
      Batch Size: 8
      Epochs: 15
      Pretrained: ImageNet-21K
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 76.93
        Top 5 Accuracy: 93.27
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_jointST_8x32x1_15e_8xb8_kinetics400_rgb/20220614_180320.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_jointST_8x32x1_15e_8xb8_kinetics400_rgb/timesformer_jointST_8x32x1_15e_8xb8_kinetics400_rgb_20220815-8022d1c0.pth

  - Name: timesformer_spaceOnly_8x32x1_15e_8xb8_kinetics400_rgb
    Config: configs/recognition/timesformer/timesformer_spaceOnly_8x32x1_15e_8xb8_kinetics400_rgb.py
    In Collection: TimeSformer
    Metadata:
      Architecture: TimeSformer
      Batch Size: 8
      Epochs: 15
      Pretrained: ImageNet-21K
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 76.98
        Top 5 Accuracy: 92.83
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_spaceOnly_8x32x1_15e_8xb8_kinetics400_rgb/20220615_101108.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/timesformer/timesformer_spaceOnly_8x32x1_15e_8xb8_kinetics400_rgb/timesformer_spaceOnly_8x32x1_15e_8xb8_kinetics400_rgb_20220815-78f05367.pth
