Collections:
  - Name: AGCN
    README: configs/skeleton/2s-agcn/README.md
    Paper:
      URL: https://arxiv.org/abs/1805.07694
      Title: 'Two-Stream Adaptive Graph Convolutional Networks for Skeleton-Based Action Recognition'

Models:
  - Name: 2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d
    Config: configs/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d.py
    In Collection: AGCN
    Metadata:
      Architecture: AGCN
      Batch Size: 16
      Epochs: 80
      Parameters: 3472176
      Training Data: NTU60-XSub
      Training Resources: 4 GPUS
    Results:
      Dataset: NTU60-XSub
      Task: Skeleton-based Action Recognition
      Metrics:
        Top 1 Accuracy: 85.92
    Training Log: https://download.openmmlab.com/mmaction/v1.0/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d/2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d/2sagcn_4xb16-80e_ntu60-xsub-keypoint-3d_20220918-3108f53f.pth

  - Name: 2sagcn_4xb16-80e_ntu60-xsub-bone-3d
    Config: configs/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-bone-3d.py
    In Collection: AGCN
    Metadata:
      Architecture: AGCN
      Batch Size: 16
      Epochs: 80
      Parameters: 3472176
      Training Data: NTU60-XSub
      Training Resources: 4 GPUS
    Results:
      Dataset: NTU60-XSub
      Task: Skeleton-based Action Recognition
      Metrics:
        Top 1 Accuracy: 87.02
    Training Log: https://download.openmmlab.com/mmaction/v1.0/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-bone-3d/2sagcn_4xb16-80e_ntu60-xsub-bone-3d.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/skeleton/2s-agcn/2sagcn_4xb16-80e_ntu60-xsub-bone-3d/2sagcn_4xb16-80e_ntu60-xsub-bone-3d_20220918-46a76b9b.pth
