Collections:
  - Name: TRN
    README: configs/recognition/trn/README.md
    Paper:
      URL: https://arxiv.org/abs/1711.08496
      Title: 'Temporal Relational Reasoning in Videos'

Models:
  - Name: trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb
    Config: configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.py
    In Collection: TRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 50
      FLOPs: 42.94G
      params: 26.64M
      Pretrained: ImageNet
      Resolution: 224x224
      Training Data: SthV1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: SthV1
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 33.65
        Top 1 Accuracy (efficient): 31.60
        Top 5 Accuracy: 62.22
        Top 5 Accuracy (efficient): 60.15
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv1-rgb_20220815-e13db2e9.pth

  - Name: trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb
    Config: configs/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb.py
    In Collection: TRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 50
      FLOPs: 42.94G
      params: 26.64M
      Pretrained: 224x224
      Resolution: height 240
      Training Data: SthV2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: SthV2
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 51.20
        Top 1 Accuracy (efficient): 47.65
        Top 5 Accuracy: 78.42
        Top 5 Accuracy (efficient): 76.27
    Training Log: https://download.openmmlab.com/mmaction/v1.0/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb.log
    Weights: https://download.openmmlab.com/mmaction/v1.0/recognition/trn/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb/trn_imagenet-pretrained-r50_8xb16-1x1x8-50e_sthv2-rgb_20220815-e01617db.pth
