Collections:
  - Name: TRN
    README: configs/recognition/trn/README.md
    Paper:
      URL: https://arxiv.org/abs/1711.08496
      Title: 'Temporal Relational Reasoning in Videos'
Models:
  - Name: trn_r50_1x1x8_50e_8xb16_sthv1_rgb
    Config: configs/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv1_rgb.py
    In Collection: TRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 50
      Parameters: 26641154
      Pretrained: ImageNet
      Resolution: height 100
      Training Data: SthV1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: SthV1
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 33.86
        Top 1 Accuracy (efficient): 31.81
        Top 5 Accuracy: 62.24
        Top 5 Accuracy (efficient): 60.47
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv1_rgb/20220808_143221.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv1_rgb/trn_r50_1x1x8_50e_8xb16_sthv1_rgb_20220815-e13db2e9.pth

  - Name: trn_r50_1x1x8_50e_8xb16_sthv2_rgb
    Config: configs/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv2_rgb.py
    In Collection: TRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 50
      Parameters: 26641154
      Pretrained: ImageNet
      Resolution: height 240
      Training Data: SthV2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: SthV2
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 51.53
        Top 1 Accuracy (efficient): 48.54
        Top 5 Accuracy: 78.60
        Top 5 Accuracy (efficient): 76.53
    Training Log: https://download.openmmlab.com/mmaction/v2.0/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv2_rgb/20220808_143256.log
    Weights: https://download.openmmlab.com/mmaction/v2.0/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv2_rgb/trn_r50_1x1x8_50e_8xb16_sthv2_rgb_20220815-e01617db.pth
