model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='EVL',
        num_frames=8,
        backbone_name='ViT-B/16',
        backbone_type='clip',
        backbone_mode='freeze_fp16',
        decoder_num_layers=4),
    cls_head=dict(
        type='I3DHead',
        num_classes=400,
        in_channels=768,
        spatial_type=None,
        dropout_ratio=0.5,
        init_std=0.01,
        average_clips='prob'),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        format_shape='NCTHW'))
