Collections:
- Name: ACRN
  README: configs/detection/acrn/README.md
  Paper:
    URL: https://arxiv.org/abs/1807.10982
    Title: "Actor-Centric Relation Network"

Models:
  - Name: slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava_rgb
    Config: configs/detection/ava/slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava_rgb.py
    In Collection: ACRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 10
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.1
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 27.58

  - Name: slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava22_rgb
    Config: configs/detection/ava/slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava22_rgb.py
    In Collection: ACRN
    Metadata:
      Architecture: ResNet50
      Batch Size: 8
      Epochs: 10
      Pretrained: Kinetics-400
      Resolution: short-side 320
      Training Data: AVA v2.2
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
      - Dataset: AVA v2.1
        Task: Action Detection
        Metrics:
              mAP: 27.63
